# Generated by Django 2.2.2 on 2019-07-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FibNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_number', models.DecimalField(decimal_places=0, max_digits=99, verbose_name='Número')),
                ('fib_number', models.DecimalField(decimal_places=0, max_digits=99, null=True, verbose_name='Fibonacci Número')),
            ],
        ),
    ]
